thesis/thesis/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
	url(r'^webapp/', include('webapp.urls')),
    url(r'^admin/', admin.site.urls),
]

thesis/webapp/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'webapp'
urlpatterns = [
	url(r'^login/$', auth_views.login, {'template_name': 'webapp/home.html'}, name='login'),
	# url(r'^login', views.login_user, name='login'),
    url(r'^index', views.index, name='index'),
    url(r'^register', views.register, name='register'),
    url(r'^home', views.home, name='home'),
    url(r'^csv', views.csv, name='csv'),
    url(r'^recordweather', views.weatherdata, name='recordweather'),
    url(r'^recordpower', views.powerdata, name='recordpower'),
    url(r'^weather', views.weather, name='weather'),
    url(r'^power', views.power, name='power'),
    url(r'^hourlypower', views.HourlyPower.as_view(), name='hourlypower'),
    url(r'^powbar', views.PowerGraph.as_view(), name='powbar'),
    url(r'^dbbar', views.AdvancedGraph.as_view(), name='dbbar'),
]

thesis/webapp/models.py
from django.db import models
from django.utils.timezone import now
from django.conf import settings
from django.contrib.auth.models import User

class RawData_Weather(models.Model):
	winddir = models.IntegerField(null=True)
	windspeedmph = models.FloatField(null=True)
	windspdmph_avg2m = models.FloatField(null=True)
	rainin = models.FloatField(null=True)
	dailyrainin = models.FloatField(null=True)
	humidity = models.FloatField(null=True)
	tempf = models.FloatField(null=True)
	pressure = models.FloatField(null=True)
	timestamp = models.DateTimeField('date logged', default = now)

class RawData_AMPS(models.Model):
	grid = models.FloatField(null=True)
	load = models.FloatField(null=True)
	batt_curr = models.FloatField(null=True)
	batt_volt = models.FloatField(null=True)
	batt_pow = models.FloatField(null=True)
	SP_curr = models.FloatField(null=True)
	SP_volt = models.FloatField(null=True)
	SP_pow = models.FloatField(null=True)
	# measured = models.FloatField(null=True)
	# predicted = models.FloatField(null=True)
	timestamp = models.DateTimeField('date logged', default = now)
	owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

thesis/webapp/forms.py
from .models import RawData_Weather
from django import forms
from django.contrib.auth.models import User


class UploadCSVFile(forms.Form):
    csvfile = forms.FileField()
    owner = forms.ModelChoiceField(
        label="Owner",
        queryset=User.objects.order_by('username'),
        required=True,
        empty_label='Choose an owner'
    )

class recordWeather(forms.ModelForm):
    winddir = forms.FloatField(label="Wind Direction", required=True,)
    windspeedmph = forms.FloatField(label="Wind Speed (mph)", required=True,)
    windspdmph_avg2m = forms.FloatField(label="Wind Speed (mph) Average", required=True,)
    rainin = forms.FloatField(label="Rain", required=True,)
    dailyrainin = forms.FloatField(label="Total Rain", required=True,)
    humidity = forms.FloatField(label="Humidity", required=True,)
    tempf = forms.FloatField(label="Temperature", required=True,)
    pressure = forms.FloatField(label="Pressure", required=True,)

    class Meta:
        model = RawData_Weather
        fields = ['winddir', 'windspeedmph', 'windspdmph_avg2m', 'rainin', 'dailyrainin', 'humidity', 'tempf', 'pressure']


class recordPower(forms.Form):
    grid = forms.FloatField(label="Grid", required=True,)
    load = forms.FloatField(label="Load", required=True,)
    batt_curr = forms.FloatField(label="Battery Current", required=True,)
    batt_pow = forms.FloatField(label="Battery Power", required=True,)
    SP_curr = forms.FloatField(label="Solar Panel Current", required=True,)
    SP_volt = forms.FloatField(label="Solar Panel Voltage", required=True,)
    owner = forms.ModelChoiceField(
        label="Owner",
        queryset=User.objects.order_by('username'),
        required=True,
        empty_label='Choose an owner'
    )


class recordUser(forms.Form):
    username = forms.RegexField(regex=r'^\w+$', widget=forms.TextInput(attrs=dict(required=True, max_length=30)), label=("Username"), error_messages={ 'invalid': ("This value must contain only letters, numbers and underscores.") })
    first_name = forms.CharField(label = "First Name")
    last_name = forms.CharField(label = "Last Name")
    email = forms.EmailField(widget=forms.TextInput(attrs=dict(required=True, max_length=30)), label=("Email address"))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs=dict(required=True, max_length=30, render_value=False)), label=("Password"))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs=dict(required=True, max_length=30, render_value=False)), label=("Password (again)"))
 
    def clean_username(self):
        try:
            user = User.objects.get(username__iexact=self.cleaned_data['username'])
        except User.DoesNotExist:
            return self.cleaned_data['username']
        raise forms.ValidationError(("The username already exists. Please try another one."))
 
    def clean(self):
        if 'password1' in self.cleaned_data and 'password2' in self.cleaned_data:
            if self.cleaned_data['password1'] != self.cleaned_data['password2']:
                raise forms.ValidationError(("The two password fields did not match."))
        return self.cleaned_data

thesis/webapp/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404
# from django.cache import cache
from django.utils import timezone
from django.contrib import messages
from webapp.forms import UploadCSVFile, recordUser, recordWeather, recordPower
from webapp.utils import handle_upload_file
from highcharts.views import (HighChartsMultiAxesView, HighChartsStockView)
from .models import RawData_AMPS, RawData_Weather
from django.views.decorators.csrf import csrf_protect
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render_to_response,HttpResponseRedirect
from django.template import RequestContext
from django.db.models import Count, Avg, DateTimeField	
from django.db.models.functions import Trunc
# Create your views here.

def index(request):
	return render(request, 'webapp/home.html')

def home(request):
	return render(request, 'webapp/home2.html')

def weather(request):
	data = RawData_Weather.objects.last()
	return render(request, 'webapp/weather.html', {"data":data})

@login_required()
def power(request):
	data = RawData_AMPS.objects.filter(owner = request.user).last()
	return render(request, 'webapp/power1.html', {"data":data})

def csv(request):
	if request.method == 'POST':
		form = UploadCSVFile(request.POST, request.FILES)	
		
		if form.is_valid():
			owner = form.cleaned_data['owner']
			handle_upload_file(request.FILES['csvfile'], owner)
			messages.success(request, 'Record saved')
	else:
		form = UploadCSVFile()

	return render(request, 'webapp/csv.html', {'form': form})

def weatherdata(request):
	if request.method == 'POST':
		form = recordWeather(request.POST)
		if form.is_valid():
			winddir = form.cleaned_data['winddir']
			windspeedmph = form.cleaned_data['windspeedmph']
			windspdmph_avg2m = form.cleaned_data['windspdmph_avg2m']
			rainin = form.cleaned_data['rainin']
			dailyrainin = form.cleaned_data['dailyrainin']
			humidity = form.cleaned_data['humidity']
			pressure = form.cleaned_data['pressure']
			dt = timezone.now()
			dt = dt.replace(second=0, microsecond=0)
			record = RawData_Weather(winddir=winddir, windspeedmph=windspeedmph, windspdmph_avg2m=windspdmph_avg2m, rainin=rainin, dailyrainin=dailyrainin, humidity=humidity, pressure=pressure, timestamp = dt)
			record.save()
			messages.success(request, 'Record saved')
	else:
		form = recordWeather()

	return render(request, 'webapp/recordweather.html', {'form': form})

def powerdata(request):
	if request.method == 'POST':
		form = recordPower(request.POST)
		if form.is_valid():
			grid = form.cleaned_data['grid']
			load = form.cleaned_data['load']
			batt_curr = form.cleaned_data['batt_curr']
			batt_pow = form.cleaned_data['batt_pow']
			SP_curr = form.cleaned_data['SP_curr']
			SP_volt = form.cleaned_data['SP_volt']
			owner = form.cleaned_data['owner']
			dt = timezone.now()
			dt = dt.replace(second=0, microsecond=0)
			record = RawData_AMPS(grid=grid, load=load, batt_curr=batt_curr, batt_pow=batt_pow, SP_curr=SP_curr, SP_volt=SP_volt, owner=owner, timestamp = dt)				
			record.save()
			messages.success(request, 'Record saved')
	else:
		form = recordPower()
	return render(request, 'webapp/recordpower.html', {'form': form})

@csrf_protect
def register(request):
	if request.method == 'POST':
		user_form = recordUser(request.POST)
		if user_form.is_valid():
			user = User.objects.create_user(
			username=user_form.cleaned_data['username'],
			password=user_form.cleaned_data['password1'],
			email=user_form.cleaned_data['email'],
			first_name=user_form.cleaned_data['first_name'],
			last_name=user_form.cleaned_data['last_name']
			)
	else:
		user_form = recordUser()
	return render(request, 'webapp/registration.html', {'user_form' : user_form})

def login_user(request):
    logout(request)
    username = password = ''
    if request.POST:
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('webapp/home/')
    return render_to_response('webapp/login.html', RequestContext(request))

# def test_display_historical(request):
# 	# processed_data = RawData_Weathe r.objects.filter(timestamp=).aggregate(Avg('load'))
# 	return render(request, 'webapp/index.html')#, processed_data)

def fetch_recent_data(user, lifetime=60):
	data = cache.get(user)
	# if data = None:
	# 	update_data.delay(user, lifetime)
	# 	data = None
	# else:
	# 	recent, expiry = data
	# 	if exprixy < datetime.datetime.now()
	# 	update_data.delay(user, lifetime)
	return data

class AdvancedGraph(HighChartsMultiAxesView):
	title = 'Weather Data'
	subtitle = ''
	chart_type = ''
	chart = {'zoomType': 'xy'}
	tooltip = {'shared': 'true'}
	legend = {
		'layout': 'vertical',
		'align': 'left',
		'verticalAlign': 'top',
		'y': 30
	}

	def get_data(self):
		data = {'id': [], 'windspeedmph': [], 'temperature':[], 'timestamp':[], 'rainin':[], 'humidity':[], 'pressure':[]}
		f = RawData_Weather.objects.all().order_by('-id')[:10][::-1]
		for unit in f:
			data['id'].append(unit.id)
			data['timestamp'].append(unit.timestamp.strftime('%I:%M %p'))
			data['windspeedmph'].append(unit.windspeedmph)
			data['temperature'].append(unit.tempf)
			data['rainin'].append(unit.rainin)
			data['humidity'].append(unit.humidity)
			data['pressure'].append(unit.pressure)


		self.categories = data['timestamp']
		 	
		self.yaxis = {
			'title': {
				'text': ''
			},
			'plotLines': [
				{
					'value': 0,
					'width': 1,
					'color': '#808080'
				}
			]
		}
		self.serie = [
			{
			'name': 'Humidty',
			'data': data['humidity']
			},
			{
			'name': 'Pressure',
			'data': data['pressure']
			},
			{
			'name': 'Rainfall',
			'data': data['rainin']
			},
			{
			'name': 'Temperature',
			'data': data['temperature']
			},
			{
			'name': 'Wind Speed',
			'data': data['windspeedmph']
			}

		]

		##### X LABELS
		# self.axis = data['id']
		

		##### SERIES WITH VALUES
		self.series = self.serie
		data = super(AdvancedGraph, self).get_data()
		return data

class PowerGraph(HighChartsMultiAxesView):
	title = 'Power'
	subtitle = ''
	chart_type = ''
	chart = {'zoomType': 'xy'}
	tooltip = {'shared': 'true'}
	legend = {
		'layout': 'vertical',
		'align': 'left',
		'verticalAlign': 'top',
		'y': 30
	}


	def get_data(self):
		data = {'id': [], 'SP_pow':[], 'timestamp':[], 'load':[]}
		f = RawData_AMPS.objects.filter(owner = User.objects.get(username=self.request.user)).order_by('-id')[:10][::-1]
		# f = RawData_AMPS.objects.filter(owner = User.objects.get(username='rizzah')).order_by('-id')[:10][::-1]
		for unit in f:
			data['id'].append(unit.id)
			data['timestamp'].append(unit.timestamp.strftime('%I:%M %p'))
			data['load'].append(unit.load)
			data['SP_pow'].append(unit.SP_pow)


		self.categories = data['timestamp']
		
		self.yaxis = {
			'title': {
				'text': 'Title 1'
			},
			'plotLines': [
				{
					'value': 0,
					'width': 1,
					'color': '#808080'
				}
			]
		}
		self.serie = [
			{
			'name': 'Load Consumption',
			'data': data['load']
			},
			{
			'name': 'Power Generated',
			'data': data['SP_pow']
			} 
		]

		##### X LABELS
		# self.axis = data['id']
		
		##### SERIES WITH VALUES
		self.series = self.serie
		data = super(PowerGraph, self).get_data()
		return data

class HourlyPower(HighChartsMultiAxesView):
	title = 'Power'
	subtitle = ''
	chart_type = ''
	chart = {'zoomType': 'xy'}
	tooltip = {'shared': 'true'}
	legend = {
		'layout': 'vertical',
		'align': 'left',
		'verticalAlign': 'top',
		'y': 30
	}
	def get_data(self):
		# data = {'id': [], 'load': [], 'SP_pow':[], 'timestamp':[]}
		data = {'load': [], 'timestamp':[]}
		# f = RawData_AMPS.objects.filter(owner = User.objects.get(username=self.request.user))[:10]
		f = RawData_AMPS.objects.filter(owner = User.objects.get(username=self.request.user)).annotate(start_day=Trunc('timestamp', 'day', output_field=DateTimeField())).values('start_day').annotate(load_day=Avg('load'))
		for unit in f:
			# data['id'].append(unit.id)
			data['timestamp'].append(unit.values('start_day'))
			data['load'].append(unit.valuess('load'))
			# data['SP_pow'].append(unit.SP_pow)


		self.categories = data['timestamp']
		
		self.yaxis = {
			'title': {
				'text': 'Title 1'
			},
			'plotLines': [
				{
					'value': 0,
					'width': 1,
					'color': '#808080'
				}
			]
		}
		self.serie = [
			{
			'name': 'Load',
			'data': data['load']
			}
			# {
			# 'name': 'Power Generated',
			# 'data': data['SP_pow']
			# } 
		]

		##### X LABELS
		# self.axis = data['id']
		
		##### SERIES WITH VALUES
		self.series = self.serie
		data = super(HourlyPower, self).get_data()
		return data

thesis/webapp/templates/webapp/csv.html
{% load static %}

<html>
    <head>
        <title>Data from CSV</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'hmain/record.css' %}" />
        <link rel='stylesheet' href='/hmain/record.css' type='text/css' media='screen'>
    </head>
    <body>

    <div class="container">

        <div class="row">
            <div class="col-lg-3 col-lg-offset-5 centered">
                <h1>Data from CSV</h1>
            </div>
        </div>

        <div class="row">
            {% if messages %}
            <ul class="messages">
                {% for msg in messages %}       
                <li>
                    <div class="alert alert-{{msg.level_tag}}" role="alert">
                {{msg.message}}
                </div>
                </li>
                {% endfor %}
            </ul>
            {% endif %}
        </div>

        <div class="content container">
            <div class="row">
                <div class = "col-lg-3 col-lg-offset-5 centered" >
                    <form enctype="multipart/form-data" method="POST" action="">
                        {% csrf_token %}
                        <div class="btn-seperator">
                            <div>{{ form }}</div>
                            <button type="submit" class="save btn btn-default" name="action" value="add_csv">Upload</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    </body>
</html>

thesis/webapp/templates/webapp/login.html
{% load static %}
<!DOCTYPE html>
<!---THIS ONE-->
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
  <title>Solar Power Management</title>

  <!-- CSS  -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href={% static 'webapp/materialize.css' %} type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href={% static 'webapp/style.css' %} type="text/css" rel="stylesheet" media="screen,projection"/>
</head>
<body bgcolor = "#B3E5FC">
  <div class = "navbar-fixed">
  <nav class="light-blue accent-4" role="navigation">
    <div class="nav-wrapper container">
      <a id="logo-container" href="#" class="brand-logo center">
      <span class = "grey-text text-darken-3">
      Solar Energy Management</a></span>
      <ul class="left hide-on-med-and-down">
        <li>
          <a href="index"><img class = "responsive-img" src={% static 'webapp/images/nl2.png' %} width = "50" height = "50"></a>
          </li>
      </ul>
      <ul class="right hide-on-med-and-down">
        <li>
          <a href="index">
              <script type="text/javascript">
                
                tmonth=new Array("January","February","March","April","May","June","July","August","September","October","November","December");

                function GetClock(){
                var d=new Date();
                var nday=d.getDay(),nmonth=d.getMonth(),ndate=d.getDate(),nyear=d.getYear();
                if(nyear<1000) nyear+=1900;
                var nhour=d.getHours(),nmin=d.getMinutes(),nsec=d.getSeconds(),ap;

                if(nhour==0){ap=" AM";nhour=12;}
                else if(nhour<12){ap=" AM";}
                else if(nhour==12){ap=" PM";}
                else if(nhour>12){ap=" PM";nhour-=12;}

                if(nmin<=9) nmin="0"+nmin;
                if(nsec<=9) nsec="0"+nsec;

                document.getElementById('clockbox').innerHTML=""+tmonth[nmonth]+" "+ndate+", "+nyear+" "+nhour+":"+nmin+":"+nsec+ap+"";
                }

                window.onload=function(){
                GetClock();
                setInterval(GetClock,1000);
                }
                </script>
                <div id="clockbox"></div>


          </a>
          </li>
      </ul>

      <ul id="nav-mobile" class="side-nav">
        <li><a href="#"><img class = "responsive-img" src={% static 'webapp/images/sol0.png' %}></a></li>
      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>
  </nav>
  </div>
<div class = "container">
   <div class="row">

      
      <div class = "col s12"><br></div>
      <div class = "col s12">
        
      </div>
      <div class = "col s12">
      <center>
      <img class = "responsive-img" src={% static 'webapp/images/Landing.png' %}  >
       </center>
        <br></div>
        <div class = "col s4">
        </div>
        <div class = "col s4">
      
          <div class="cardlight-blue lighten-4">
            <div class="card-content black-text">
              
                          <div class="row">
                <div class="input-field col s12">
                 <div id="login">
                  <form method="post" action="{%url 'webapp:login'%}">
                    {%csrf_token%}
                    <table>
                      <tr>
                        <td> {{form.username.label_tag}}</td>
                        <td> {{form.username}}</td>
                      </tr>
                       <tr>
                        <td> {{form.password.label_tag}}</td>
                        <td> {{form.password}}</td>
                      </tr>
                    </table>
                    <input type ="submit" value="login"/>
                    <input type ="hidden" name="next" value="{%url 'webapp:home'%}"/>
            </div>
        </div>
        </form>
    </div>
            </div>
            
          </div>
     
      </div>
 
  </div>
</div>
      
<br>
<br>


</div>   

 



  <!--  Scripts-->
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/js/materialize.min.js"></script>
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script>
   $(document).ready(function () {
       $('.slider').slider({full_width: true});
   });
    
</script>
<script>
     $(document).ready(function(){
    // the "href" attribute of .modal-trigger must specify the modal ID that wants to be triggered
    $('.modal').modal();
  });
         
</script>
  <script src={% static 'js/materialize.js' %}></script>
  <script src={% static 'js/init.js' %}></script>
  </body>
</html>

thesis/webapp/templates/webapp/recordpower.html
{% load static %}

<html>
    <head>
        <title>New Record</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    </head>
    <body>

    <div class="container">

    	<div class="row">
    		<div class="col-lg-3 col-lg-offset-5 centered">
            	<h1>New Record</h1>
            </div>
        </div>

        <div class="row">
			{% if messages %}
			<ul class="messages">
			    {% for msg in messages %}       
			    <li>
			        <div class="alert alert-{{msg.level_tag}}" role="alert">
			 	{{msg.message}}
				</div>
			    </li>
			    {% endfor %}
			</ul>
			{% endif %}
		</div>

        <div class="content container">
            <div class="row">
            	<div style = "text-align: center;">
	            <form method="POST">
	            	{% csrf_token %}
	    			<div class="form-group">	
						<label for="{{ form.grid.id_for_label }}">Grid: </label>
						<div>{{ form.grid }}</div>
						
					</div>
	    			<div class="form-group">	
						<label for="{{ form.load.id_for_label }}">Load: </label>
						<div>{{ form.load }}</div>
					</div>
	    			<div class="form-group">	
						<label for="{{ form.batt_curr.id_for_label }}">Battery Current: </label>
						<div>{{ form.batt_curr }}</div>
					</div>
					<div class="form-group">
    					<label for="{{ form.batt_pow.id_for_label }}">Battery Power: </label>
    					<div>{{ form.batt_pow }}</div>
					</div>
					<div class="form-group">
    					<label for="{{ form.SP_volt.id_for_label }}">Solar Panel Voltage: </label>
    					<div>{{ form.SP_volt }}</div>
					</div>
					<div class="form-group">
    					<label for="{{ form.SP_curr.id_for_label }}">Solar Panel Current: </label>
    					<div>{{ form.SP_curr }}</div>
					</div>
	        		<button type="submit" class="save btn btn-default">Save</button>
    			</form>
    			<a class="btn btn-link" href="{% url 'webapp:index'%}">Go back to Menu</a>
    			</div>
            </div>
        </div>
    </div>

    </body>
</html>

thesis/webapp/templates/webapp/recordweather.html
{% load static %}

<html>
    <head>
        <title>New Record</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    </head>
    <body>

    <div class="container">

    	<div class="row">
    		<div class="col-lg-3 col-lg-offset-5 centered">
            	<h1>New Record</h1>
            </div>
        </div>

        <div class="row">
			{% if messages %}
			<ul class="messages">
			    {% for msg in messages %}       
			    <li>
			        <div class="alert alert-{{msg.level_tag}}" role="alert">
			 	{{msg.message}}
				</div>
			    </li>
			    {% endfor %}
			</ul>
			{% endif %}
		</div>

        <div class="content container">
            <div class="row">
            	<div style = "text-align: center;">
	            <form method="POST">
	            	{% csrf_token %}
	    			<div class="form-group">	
						<label for="{{ form.winddir.id_for_label }}">Wind Direction: </label>
						<div>{{ form.winddir }}</div>
						
					</div>
	    			<div class="form-group">	
						<label for="{{ form.windspeedmph.id_for_label }}">Wind Speed (mph): </label>
						<div>{{ form.windspeedmph }}</div>
					</div>
	    			<div class="form-group">	
						<label for="{{ form.windspdmph_avg2m.id_for_label }}">Wind Speed (mph) Average: </label>
						<div>{{ form.windspdmph_avg2m }}</div>
					</div>
					<div class="form-group">
    					<label for="{{ form.rainin.id_for_label }}">Rain: </label>
    					<div>{{ form.rainin }}</div>
					</div>
					<div class="form-group">
    					<label for="{{ form.dailyrainin.id_for_label }}">Total Rain: </label>
    					<div>{{ form.dailyrainin }}</div>
					</div>
					<div class="form-group">
    					<label for="{{ form.humidity.id_for_label }}">Humidity: </label>
    					<div>{{ form.humidity }}</div>
					</div>
					<div class="form-group">
    					<label for="{{ form.tempf.id_for_label }}">Temperature: </label>
    					<div>{{ form.tempf }}</div>
					</div>
					<div class="form-group">
    					<label for="{{ form.pressure.id_for_label }}">Pressure: </label>
    					<div>{{ form.pressure }}</div>
					</div>
	        		<button type="submit" class="save btn btn-default">Save</button>
    			</form>
    			<a class="btn btn-link" href="{% url 'webapp:index'%}">Go back to Menu</a>
    			</div>
            </div>
        </div>
    </div>

    </body>
</html>

thesis/webapp/templates/webapp/trialhighcharts.html
<script src="/static/js/jquery-2.1.0.min.js"></script>
<script src="/static/js/stock/highstock.js"></script>
<script src="/static/js/stock/modules/exporting.js"></script>

<div id="stock_panel" class="stock-body" style="width:100%;height:314px"></div>

<script type="text/javascript">
$(function(){
        var chartDataUrl = "{% url 'webapp:weathersample' %}";
        $.getJSON(chartDataUrl,
            function(data) {
        // Create the chart
        $('#stock_panel').highcharts('StockChart', {

            rangeSelector : {
                selected : 1,
                inputEnabled: $('#stock_panel').width() > 480
            },

            title : {
                text : 'fish Price'
            },

            series : [{
                name : 'chart_data',
                data : data,
                tooltip: {
                    valueDecimals: 2
                }
            }]
        });
    });

});

</script>